AWSTemplateFormatVersion: 2010-09-09
Description: Construye los parametros

Parameters:
  prefijo:
    Type: String
    Description: Abreviatura del nombre de la cuenta AWS en minusculas.
    Default: ''

  correoseguridad:
    Type: String
    Description: Correo para notificacion de eventos de seguridad
    Default: ''

Resources:
  ParametroAbreviaturaCuenta:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Abreviatura de la cuenta AWS
      Name: /cuenta/prefijo
      Type: String
      Value: !Ref prefijo

  ParametroCorreoNotificacion:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Correo para notificacion de eventos de seguridad
      Name: /seguridad/correo
      Type: String
      Value: !Ref correoseguridad
