AWSTemplateFormatVersion: 2010-09-09

Description: Crea llaves de cifrado para CloudTrail y CloudWatch

Resources:
# --------------- #
# CLOUDTRAIL #
# --------------- #
    LlaveCloudTrail:
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Type: AWS::KMS::Key
      Properties:
        Description: Llave para encriptar CloudTrail 
        EnableKeyRotation: true
        KeyPolicy:
          Version: 2012-10-17
          Id: LlaveCloudTrail
          Statement:
            - Sid: Habilitar permisos IAM
              Effect: Allow
              Principal:
                AWS: !Join
                  - ''
                  - - 'arn:aws:iam::'
                    - !Ref 'AWS::AccountId'
                    - ':root'
              Action: 'kms:*'
              Resource: '*'
            
            - Sid: Permitir a CloudTrail encriptar con esta llave
              Effect: Allow
              Principal:
                Service:
                  - cloudtrail.amazonaws.com
              Action: 'kms:GenerateDataKey*'
              Resource: '*'
              Condition: 
                StringLike:
                  'kms:EncryptionContext:aws:cloudtrail:arn': !Sub 'arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*'

            - Sid: Permitir a CloudTrail desencriptar con esta llave
              Effect: Allow
              Principal:
                Service:
                  - cloudtrail.amazonaws.com
              Action: 'kms:Decrypt'
              Resource: '*'
              Condition: 
                StringEquals:
                  'kms:CallerAccount': !Sub '${AWS::AccountId}'
                StringLike:
                  'kms:EncryptionContext:aws:cloudtrail:arn': !Sub 'arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*'

            - Sid: Permitir a CloudTrail describir esta llave
              Effect: Allow
              Principal:
                Service: cloudtrail.amazonaws.com
              Action: 'kms:DescribeKey'
              Resource: '*'
    
    AliasLlaveCloudTrail:
      Type: AWS::KMS::Alias
      Properties:
        AliasName: alias/llavecloudtrail
        TargetKeyId:
          Ref: LlaveCloudTrail

    ParametrosLlaveCloudTrail:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Description: Arn de llave para CloudTrail
        Name: /seguridad/llaves/LlaveCloudTrail
        Value: !GetAtt LlaveCloudTrail.Arn


# --------------- #
# CLOUDWATCH LOGS #
# --------------- #

    LlaveCloudWatch:
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Type: AWS::KMS::Key
      Properties:
        Description: Llave para encriptar CloudWatch Logs 
        EnableKeyRotation: true
        KeyPolicy:
          Version: 2012-10-17
          Id: LlaveCloudWatch
          Statement:
            - Sid: Habilitar permisos IAM
              Effect: Allow
              Principal:
                AWS: !Join
                  - ''
                  - - 'arn:aws:iam::'
                    - !Ref 'AWS::AccountId'
                    - ':root'
              Action: 'kms:*'
              Resource: '*'
            
            - Sid: Permitir a CloudWatch utilizar esta llave
              Effect: Allow
              Principal:
                Service: !Sub logs.${AWS::Region}.amazonaws.com
              Action: 
                  - 'kms:Encrypt'
                  - 'kms:Decrypt'
                  - 'kms:ReEncrypt'
                  - 'kms:GenerateDataKey'
              Resource: '*'
              Condition: 
                ArnEquals:
                  'kms:EncryptionContext:aws:logs:arn': !Sub 'arn:aws:logs:*:${AWS::AccountId}:*'

    AliasLlaveCloudWatch:
      Type: AWS::KMS::Alias
      Properties:
        AliasName: alias/llavecloudwatch
        TargetKeyId:
          Ref: LlaveCloudWatch

    ParametrosLlaveCloudWatch:
      Type: AWS::SSM::Parameter
      Properties:
        Type: String
        Description: Arn de llave para CloudWatchLogs
        Name: /seguridad/llaves/LlaveCloudWatch
        Value: !GetAtt LlaveCloudWatch.Arn