AWSTemplateFormatVersion: 2010-09-09
Description: Stack raiz

Parameters:
  BucketPlantillas:
    Type: String
    Description: S3 Bucket where templates are stored

  AbreviaturaCuenta:
    Type: String
    Description: Name of AWS account in lower case. No upper case or different characters are supported.
    Default: ''

  CorreoNotificacion:
    Type: String
    Description: Email to send security event notifications.
    Default: ''

  GuardDuty:
    Type: String
    Description: Amazon GuardDuty threath detection enablement.
    AllowedValues: ['true','false']
    Default: 'true'

  Macie:
    Type: String
    Description: Amazon Macie sensitive data detection enablement.
    AllowedValues: ['true','false']
    Default: 'true'

  SecurityHub:
    Type: String
    Description: AWS Security Hub findings centralization enablement. 
    AllowedValues: ['true','false']
    Default: 'true'

  CISDashboard:
    Type: String
    Description: CloudWatch dashboard with CIS alerts enablement.
    AllowedValues: ['true','false']
    Default: 'true'

Conditions:
  EnableCISDashboardCondition: !Equals [!Ref CISDashboard, 'true']

Resources:
  Parametros:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        prefijo: !Ref AbreviaturaCuenta
        correoseguridad: !Ref CorreoNotificacion
      TemplateURL: !Join 
        - ""
        - - 'https://'
          - !Ref BucketPlantillas
          - '.s3.amazonaws.com/'
          - 'plantilla-parametros.yml'
      TimeoutInMinutes: 10

  Llaves:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Join
        - ""
        - - 'https://'
          - !Ref BucketPlantillas
          - '.s3.amazonaws.com/'
          - 'plantilla-llaves.yml'      
      TimeoutInMinutes: 20
    DependsOn: Parametros
  
  Buckets:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Join
        - ""
        - - 'https://'
          - !Ref BucketPlantillas
          - '.s3.amazonaws.com/'
          - 'plantilla-buckets-seguridad.yml'      
      TimeoutInMinutes: 20
    DependsOn: Llaves

  Seguridad:
    Type: AWS::CloudFormation::Stack
    Properties:     
      Parameters:
        EnableGuardDuty: !Ref GuardDuty
        EnableMacie: !Ref Macie
        EnableSecurityHub: !Ref SecurityHub  
      TemplateURL: !Join
       - ""
       - - 'https://'
         - !Ref BucketPlantillas
         - '.s3.amazonaws.com/'
         - 'plantilla-seguridad.yml'      
      TimeoutInMinutes: 20
    DependsOn: Buckets

  Notificaciones:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ""
        - - 'https://'
          - !Ref BucketPlantillas
          - '.s3.amazonaws.com/'
          - 'plantilla-notificaciones.yml'      
      TimeoutInMinutes: 20
    DependsOn: Seguridad

  AlertasCIS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ""
        - - 'https://'
          - !Ref BucketPlantillas
          - '.s3.amazonaws.com/'
          - 'plantilla-cis-alerts.yml'      
      TimeoutInMinutes: 20
    DependsOn: Notificaciones

  DashboardCIS:
    Condition: EnableCISDashboardCondition
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ""
        - - 'https://'
          - !Ref BucketPlantillas
          - '.s3.amazonaws.com/'
          - 'plantilla-cis-dashboard.yml'      
      TimeoutInMinutes: 20
    DependsOn: AlertasCIS


